# Generated by Django 3.2.8 on 2021-10-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20211007_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logind',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
