# Generated by Django 3.2.8 on 2021-10-09 11:11

import Products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('price', models.FloatField()),
                ('main_image', models.ImageField(upload_to=Products.models.Product.get_image_path)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=Products.models.Product.get_image_path)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=Products.models.Product.get_image_path)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=Products.models.Product.get_image_path)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to=Products.models.Product.get_image_path)),
                ('image_6', models.ImageField(blank=True, null=True, upload_to=Products.models.Product.get_image_path)),
                ('image_7', models.ImageField(blank=True, null=True, upload_to=Products.models.Product.get_image_path)),
                ('image_8', models.ImageField(blank=True, null=True, upload_to=Products.models.Product.get_image_path)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
        ),
    ]
