# Generated by Django 3.2.8 on 2021-10-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20211009_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_processing',
            field=models.BooleanField(default=False),
        ),
    ]
