# Generated by Django 3.2.8 on 2021-10-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_order_in_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
