# Generated by Django 3.2.8 on 2021-10-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_auto_20211015_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderditem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
